spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  flyway:
      enabled: true
      locations: classpath:db/migration
  h2:
    console:
      enabled: true

app:
  datetime:
    format: "yyyy-MM-dd'T'HH:mm:ss"